version: '2'
.catalog:
  name: Harbor
  version: 1.1.1-1-rev1
  description: |
    Enterprise Class Container Registry [by VMware]
  minimum_rancher_version: v0.59.0
  uuid: harbor-4
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: myregistry
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "harborhostlabel"
      label: "Harbor will be deployed on the hosts with this label (default: harbor-host=true)"
      description: |
        Harbor will be deployed on hosts with this label. 
        Set the label on one host if you want Harbor to be deployed on a single host (rancher-nfs volume driver is required for multiple hosts)"
      default: harbor-host=true
      required: true
      type: "string"    
    - variable: "volumedriver"
      description: "Volume Driver being used. Set rancher-nfs if you run in distributed mode"
      label: "Volume Driver:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs
services:
  registry:
    scale: 1
  adminserver:
    scale: 1
  proxy:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line:
  jobservice:
    scale: 1
  ui:
    scale: 1
  mysql:
    scale: 1
  harbor-setupwrapper:
    scale: 1
