version: '2'
.catalog:
  name: Harbor
  version: 0.5.0-basic
  description: |
    Enterprise Class Container Registry by VMware
  minimum_rancher_version: v0.59.0
  uuid: harbor-0
  questions:
    - variable: "harborhostname"
      description: "Harbor IP, HOSTNAME or FQDN as used to acces it from the Docker CLI"
      label: "IP/Hostname/FQDN:"
      required: true
      default: myregistry
      type: "string"
    - variable: "harbor_admin_password"
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
    - variable: "harborhostlabel"
      label: "Harbor will be deployed on the host with this label (default: harbor-host=true)"
      description: |
        Harbor host label
      default: harbor-host=true
      required: true
      type: "string"
services:
  registry:
    scale: 1
  proxy:
    scale: 1
  jobservice:
    scale: 1
  ui:
    scale: 1
  mysql:
    scale: 1
  harbor-setupwrapper:
    scale: 1
