version: '2'
.catalog:
  name: Harbor
  version: 0.5.0-rancher1
  description: |
    (Experimental) Harbor
  minimum_rancher_version: v0.59.0
  uuid: harbor-0
  questions:
    - variable: "harbor_fqdn"
      description: "Harbor fqdn to acces it"
      label: "Harbor fqdn:"
      required: true
      default: myharbor.mycompany.com
      type: "string"
    - variable: "harbor_pass" 
      label: "Harbor password:"
      description: |
        Harbor admin password
      default: Vmware123!
      required: true
      type: "string"
services:
  registry:
    scale: 1
  proxy:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: 
  jobservice:
    scale: 1
  ui:
    scale: 1
  mysql:
    scale: 1
  harbor-setupwrapper:
scale: 1