# use this with `docker-compose up` against a generic Docker end-point (e.g. standalone Docker, VIC)
version: "2.1"
services:
  yelb-ui:
    image: mreferre/yelb-ui
    depends_on:
      - yelb-appserver
    ports:
      - 80:80
    networks:
      - yelb-network

  yelb-appserver:
    image: mreferre/yelb-appserver
    depends_on:
      - redis-server
    networks:
      - yelb-network

  redis-server:
    image: redis
    networks:
      - yelb-network
    # uncomment the following lines if you want to persist redis data across deployments
    #volumes:
    #  - data:/data

networks:
  yelb-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution   

# uncomment the following lines if you want to persist redis data across deployments
#volumes:
#   data:
#      driver: local # you can pick another driver depending on the platform you are deploying onto