version: '2'
services:
  harbor-setupwrapper:
    image: mreferre/harbor-setupwrapper:1.1.1-1
    container_name: harbor-setupwrapper
    environment:
      - HARBORHOSTNAME=${HARBORHOSTNAME}
      - HARBOR_ADMIN_PASSWORD=${HARBOR_ADMIN_PASSWORD}
    volumes:
      - /data:/data:z
      - /etc/registry
      - /etc/ui
      - /etc/jobservice
      - /etc/nginx
      - /configdb
      - /configui
      - /configjobservice
      - /configadminserver
    command: ["/harbor/harbor-setupwrapper.sh"]
    network_mode: "none"
  log:
    image: vmware/harbor-log:v1.1.1
    container_name: harbor-log
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
    ports:
      - 1514:514
    networks:
      - harbor
  registry:
    image: vmware/registry:photon-2.6.0
    container_name: registry
    restart: always
    volumes:
      - /data/registry:/storage:z
    volumes_from:
      - harbor-setupwrapper
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
    networks:
      - harbor
  mysql:
    image: vmware/harbor-db:v1.1.1
    container_name: harbor-db
    restart: always
    volumes:
      - /data/database:/var/lib/mysql:z
    volumes_from:
      - harbor-setupwrapper
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configdb/entrypointdb.sh
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
    networks:
      - harbor
  adminserver:
    image: vmware/harbor-adminserver:v1.1.1
    container_name: harbor-adminserver
    restart: always
    volumes:
      - /data/config/:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    volumes_from:
      - harbor-setupwrapper
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configadminserver/entrypointadminserver.sh
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
    networks:
      - harbor
  ui:
    image: vmware/harbor-ui:v1.1.1
    container_name: harbor-ui
    restart: always
    volumes:
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
    volumes_from:
      - harbor-setupwrapper
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configui/entrypointui.sh
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
    networks:
      - harbor
  jobservice:
    image: vmware/harbor-jobservice:v1.1.1
    container_name: harbor-jobservice
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - /data/secretkey:/etc/jobservice/key:z
    volumes_from:
      - harbor-setupwrapper
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configjobservice/entrypointjobservice.sh
    depends_on: 
      - log
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
    networks:
      - harbor
  proxy:
    image: vmware/nginx:1.11.5-patched
    container_name: nginx
    restart: always
    volumes_from:
      - harbor-setupwrapper
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
    networks:
      - harbor
networks:
  harbor:
    external: false
